### Criar uma categoria
POST http://localhost:8080/categorias
Content-Type: application/json

{
  "nome": "Trabalho"
}

### Listar todas as categorias
GET http://localhost:8080/categorias

### Buscar categoria por id
GET http://localhost:8080/categorias/2

### Deletar categoria por id
DELETE http://localhost:8080/categorias/1

### Editar categoria
PUT http://localhost:8080/categorias/3
Content-Type: application/json

{
  "nome": "Lazer"
}