### Criar uma tarefa
POST http://localhost:8080/tarefas
Content-Type: application/json

{
  "titulo": "Estudar é ruim",
  "concluida": false,
  "categoriaId": 1
}

### Listar todas as tarefas
GET http://localhost:8080/tarefas

### Buscar tarefa por id
GET http://localhost:8080/tarefas/4

### Deletar tarefa por id
DELETE http://localhost:8080/tarefas/1

### Editar tarefa
PUT http://localhost:8080/tarefas/4
Content-Type: application/json

{
  "titulo": "Estudar Spring Boot",
  "concluida": false,
  "categoria": {
    "id": 1
  }
}